### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by ibrumby** [fadden/ciderpress#41] opened 2020-04-11 15:01 UTC
Every time I launch Ciderpress it creates a window that is 3820 pixels wide on my monitor. So the first thing I have to do is reduce the width of the window. It would be nice if it remembered the window size.

**Comment by fadden** [comment] 2020-07-23 21:47
I'm passing `rectDefault` to the window creation function, which is documented thusly:

> Pass this static CRect as a parameter when creating a window to allow Windows to choose the window's initial size and position.

On my system, Windows chooses to make it larger than I would like, though not full screen.  I think there used to be a time when Windows would remember what you did automatically, but as of at least Win7 that is no longer the case.

The window size is set before preferences are loaded, which means I can't simply save a preference and use it later.

I think the correct approach is to use [GetWindowPlacement](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowplacement) and [SetWindowPlacement](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowplacement).  I actually use these in SourceGen, with a [WindowPlacement](https://github.com/fadden/6502bench/blob/master/CommonWPF/WindowPlacement.cs) class that makes native calls into `user32.dll` and serializes the result.  It outputs a blob of values (3 ints, 2 points, 1 rect) that would need to be stored in the Registry, since that's where CP's settings live.

Simply restoring the previous X/Y position and size is problematic on multi-monitor systems, since the external monitors frequently go away.  Anything that is placed substantially off-screen needs to be relocated and perhaps resized, or you might not be able to see the window or grab its title bar.  The window placement calls are expected to deal with that.

**Comment by fadden** [comment] 2021-04-11 21:57
I finally got around to digging into this a little more.  MFC's CWinAppEx class, from which CiderPress inherits, has an `EnableLoadWindowPlacement()` feature, and a `LoadWindowPlacement()` method that you can override to modify the position.  Apparently these are supposed to save and restore the app's window size and position in the registry, but as far as I can tell these do absolutely nothing whatsoever now.

So that might be part of why it no longer behaves the way it used to.

The key moment for picking a size seems to be `MainWindow::PreCreateWindow()`, which receives a `CREATESTRUCT` from the operating system (or whatever app launched it). The position and width/height values are being set to `CW_USEDEFAULT`, which is [documented](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexa):

> If nWidth is CW_USEDEFAULT, the system selects a default width and height for the window; the default width extends from the initial x-coordinates to the right edge of the screen; the default height extends from the initial y-coordinate to the top of the icon area.

I can trivially set a fixed size like this:

```
diff --git a/app/Main.cpp b/app/Main.cpp
index b74b9a6..8e65acc 100644
--- a/app/Main.cpp
+++ b/app/Main.cpp
@@ -311,6 +311,8 @@ BOOL MainWindow::PreCreateWindow(CREATESTRUCT& cs)
     BOOL res = CFrameWnd::PreCreateWindow(cs);

     cs.dwExStyle &= ~(WS_EX_CLIENTEDGE);
+    cs.cx = 1150;
+    cs.cy = 800;
```

Not ideal, but seems more pleasant than the current behavior.  The window's position is still determined by the OS, so it shouldn't end up off screen.  Potentially slightly awkward for somebody running at 1024x768; I could try to limit the size based on the screen metrics of the primary or current monitor ([with these calls](https://stackoverflow.com/questions/4631292/how-detect-current-screen-resolution)), though I don't know if that's a real concern in this century.

**Comment by fadden** [comment] 2021-04-19 00:23
Above workaround published in [v4.0.5-d2](https://github.com/fadden/ciderpress/releases/tag/v4.0.5-d2).

**Comment by Keatah** [comment] 2021-04-24 05:57
Ciderpress now opens full screen and then spreads half-way across my 2nd monitor. Reverting back to v4.0.5-d1, as that version works correctly.

**Comment by fadden** [comment] 2021-04-24 14:26
@Keatah Can you provide some additional details?

- What OS are you running?
- What resolution is your primary display configured for?
- What does "works correctly" mean... how big does the window usually become?  Was it previously maximized?

The change **should** force the window to be 1150x800, so unless you're running on a tiny system I'm at a bit of a loss.  Anything that would help me reproduce your circumstances would be helpful.

**Comment by Keatah** [comment] 2021-04-29 07:43
Yes, we're running at smaller resolutions. Some as small as 1024x768. Otherwise 1280x1024, 1600x1200. Not popular resolutions in today's world, I understand..

It seems ok at 1920x1200 or 1920x1080.

I wouldn't worry about it too much. Is it possible to have CP remember the previous size and position?

Win10 and sometimes WinXP.

**Comment by fadden** [comment] 2021-05-10 22:08
Version 4.0.5 was released without the fixed-size behavior (i.e. same as v4.0.5-d1).  FWIW, this is the last version that will run on WinXP.

Version 4.1.0-d1 saves and restores the main window placement: https://github.com/fadden/ciderpress/releases/tag/v4.1.0-d1

**Comment by ibrumby** [comment] 2021-05-10 22:51
It's almost perfect now. If I try and align the window with the top-left of my screen however it tends to reset to default size.I think I must be moving the window to -1 xpos or -1 ypos, but visually it looks like the window is completely on screen rather than

**Comment by fadden** [comment] 2021-05-10 22:58
Whoops, that's my fault.  It's punting if any of the values are < 0.  Easy to fix.

**Comment by fadden** [comment] 2021-05-11 00:42
This should work better: https://github.com/fadden/ciderpress/releases/tag/v4.1.0-d2

**Closed by fadden** 2021-05-11 00:42 UTC
Labels: enhancement

**Comment by ibrumby** [comment] 2021-05-11 00:48
Works great!
