### ISSUE TITLE
Ciderpress 4.03 File Viewer Copy/Paste bug?

### ISSUE THREAD

**Issue by airnocker** [fadden/ciderpress#36] opened 2019-02-15 21:09 UTC
Having used ciderpress 4.0.3 occasionally for the past few years and used it to view Applessoft Basic listings from disk images with the File Viewer, I've always had Applesoft Basic selected in the formatter drop-down list box when viewing Applesoft Basic files and simply copied & pasted the contents of the viewer to a Windows 10 text file, primarily for archiving these files to a Windows file format.

Recently, I printed out the contents of one of these text files for review and planning software updates only to find that the "/" character, which does display in File Viewer, did not and would not copy over to a Windows Notepad file no matter how many times I tried.

Here is an example line number that appears in File Viewer:  
 340  HPLOT X / S,Y / S

Here is what gets copied and pasted into Windows 10 Notepad:
 340  HPLOT X   S,Y   S

I then clicked the Best button and copied and pasted again to the Notepad file.  This time the "/" character was copied and pasted correctly.

Wouldn't it be "best" if when selecting the Applesoft Basic formatter that it defaults to Best to insure all characters would be accurately copied and pasted to another text app?

I love ciderpress and am most appreciative and thankful to Fadden for making this available to us old farts.

Regards,

airnocker

**Comment by fadden** [comment] 2019-02-15 21:41
I'm not able to reproduce this.  Steps:

1. Open the attached SHK file with CiderPress.  (I had to put it in a .zip so github would accept it.)
2. Double-click SLASH.TEST to open it in the file viewer.
3. Click in text area, then Ctrl+A to select all, Ctrl+C to copy.
4. Win+R to open "run" window, type "notepad" and hit return to start notepad.
5. In notepad, Ctrl+V to paste.

I get all of the slashes in the output.  I tried both "Applesoft BASIC" and "Applesoft BASIC w/Highlighting" modes.

I think the text copy & paste stuff is handled by the Windows RichEditCtrl.  There really shouldn't be any opportunity for CiderPress to screw things up there.

Can you attach the file that's demonstrating the problem?  Could be something specific to the file.

[slashtest.zip](https://github.com/fadden/ciderpress/files/2870952/slashtest.zip)

**Comment by fadden** [comment] 2019-04-10 22:01
Not reproducible; closing.

**Closed by fadden** 2019-04-10 22:01 UTC
Labels: bug
