### ISSUE TITLE
Massively sparse files created by CP can't be read by Copy ][+ 9.0

### ISSUE THREAD

**Issue by Keatah** [fadden/ciderpress#15] opened 2016-05-25 20:27 UTC
Ciderpress is not able to correctly determine the filesize on the HELPSCREENS file in this disk image. Copy II+ does however..

ftp://ftp.apple.asimov.com/pub/apple_II/images/masters/prodos/prodos_basic.dsk

**Comment by fadden** [comment] 2016-05-25 20:57
Here's the relevant piece of the directory entry in block 2:

    0c0: 20 41 a7 00 00 02 00 3b 48 45 4c 50 53 43 52 45   A'....;HELPSCRE
    0d0: 45 4e 53 00 00 00 00 04 49 00 3c 00 00 94 bc 41  ENS.....I.<...<A
    0e0: a7 00 00 00 00 21 00 02 41 a7 00 00 02 00 d8 50  '....!..A'....XP

According to the entry, `blocks_used` is $003c (60 blocks), and `EOF` is $bc9400 (12358656).  CiderPress is using the correct value.

The text file is massively sparse.  Given that this is a disk full of examples, it's possible that this was done deliberately to demonstrate the feature.  Looking at the file, the help text appears at offset 00c2000, 0125c00, 0131e00, and so on out to 0bc9200.

File copiers like Copy ][+ will replicate the sparse layout when duplicating the file by scanning the filesystem for the set of used blocks.  If you copied the file to a filesystem that didn't support sparse files, such as HFS, you would end up with a 12MB file, just as you do when extracting from CiderPress.

If you copy the file between ProDOS disks using CiderPress (select file, Ctrl-C, open a different disk image, Ctrl-V), the file is copied correctly... and actually uses three fewer blocks.

It's inconvenient to view the file in the CiderPress file viewer, as there's no "ignore the sparse stuff" mode, but AFAIK everything is working as intended.

**Comment by Keatah** [comment] 2016-05-27 09:13
The file can no longer be read in Copy II+ if copied to blank disk copy/paste in CP.

Copy II+ can handle the file. Copy to a new destination disk, then verify. Ok..

But when copying with copy/paste through ciderpress, the destination file doesn't verify in Copy II+. In my test, after copy/paste I got I/O ERROR $3F01 when trying to verify the newly copied file in Copy II+.

**Comment by fadden** [comment] 2016-05-27 15:09
Now I see. I'll take a look.

**Comment by fadden** [comment] 2016-05-30 01:54
ProSel utilities work just fine -- Mr. Fixit reports no errors, and Cat Doctor can copy the file just fine.  With Copy ][ Plus 9.0, I get the error:

    I/O Error: Block $3F01

If I copy HELPFILES with CiderPress, then copy the copy with Cat Doctor, the file created by Cat Doctor *can* be copied with Copy ][+.  My guess is that there is a bug in Copy ][+, exposed by some difference in the way CiderPress creates the file.

**Comment by fadden** [comment] 2016-05-30 02:10
Master index block of a ProDOS-created file:

    000: 41 00 00 00 00 00 43 00 00 45 48 00 4b 4e 51 00  A.....C..EH.KNQ.
    010: 53 00 00 00 00 00 00 56 00 58 00 00 00 00 00 00  S......V.X......
    020: 5b 00 00 00 00 5d 00 00 00 00 00 00 00 00 00 00  [....]..........
    030: 00 5f 00 00 62 00 00 00 00 00 00 00 00 00 64 00  ._..b.........d.
    040: 00 66 68 00 00 00 00 00 6b 00 6f 00 71 00 73 75  .fh.....k.o.q.su
    050: 00 00 00 00 00 77 00 00 00 00 00 00 00 00 79 00  .....w........y.
    060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................

Same for the CiderPress-created file:

    000: 00 00 00 00 00 00 29 00 00 2a 2b 00 2c 2d 2e 00  ......)..*+.,-..
    010: 2f 00 00 00 00 00 00 30 00 31 00 00 00 00 00 00  /......0.1......
    020: 32 00 00 00 00 33 00 00 00 00 00 00 00 00 00 00  2....3..........
    030: 00 34 00 00 35 00 00 00 00 00 00 00 00 00 36 00  .4..5.........6.
    040: 00 37 38 00 00 00 00 00 39 00 3a 00 3b 00 3c 3d  .78.....9.:.;.<=
    050: 00 00 00 00 00 3e 00 00 00 00 00 00 00 00 3f 00  .....>........?.
    060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................

Note the CiderPress file doesn't have an entry for position zero.  The ProDOS-created file references index block 41, which has a single data block (40).  Block 40 is filled entirely with zeroes.

There is no need to have that first index and data block; it's why the CiderPress-created file is two blocks shorter.  The ProDOS file has those blocks allocated because the file expanded from "seedling" to "sapling" to "tree" as more data was written to it, and ProDOS never went back and cleared out the first unnecessary block.

I don't know why Copy ][+ is failing.  As far as I can tell, the file structure is correct, just different from what you get when a file "evolves".  (CiderPress knows the full file size ahead of time, so it creates the "tree" structure immediately.)

In theory the problem could be avoided by modifying CiderPress to always allocate the first block of the file, but it's also possible to work around the problem by using a different copy program.

**Comment by fadden** [comment] 2021-07-24 15:04
Fixed in v4.1.0-d3.

**Closed by fadden** 2021-07-24 15:04 UTC
Labels: bug
